import type { ToolSpec } from "../../types.js";

export const core_competency_tools: ToolSpec[] = [
  {
    name: "core_competency_add_competency_to_course",
    moodleFunction: "core_competency_add_competency_to_course",
    description: "Moodle web service function `core_competency_add_competency_to_course`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_add_competency_to_plan",
    moodleFunction: "core_competency_add_competency_to_plan",
    description: "Moodle web service function `core_competency_add_competency_to_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_add_competency_to_template",
    moodleFunction: "core_competency_add_competency_to_template",
    description: "Moodle web service function `core_competency_add_competency_to_template`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_add_related_competency",
    moodleFunction: "core_competency_add_related_competency",
    description: "Moodle web service function `core_competency_add_related_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_approve_plan",
    moodleFunction: "core_competency_approve_plan",
    description: "Moodle web service function `core_competency_approve_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_competency_framework_viewed",
    moodleFunction: "core_competency_competency_framework_viewed",
    description: "Moodle web service function `core_competency_competency_framework_viewed`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_competency_viewed",
    moodleFunction: "core_competency_competency_viewed",
    description: "Moodle web service function `core_competency_competency_viewed`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_complete_plan",
    moodleFunction: "core_competency_complete_plan",
    description: "Moodle web service function `core_competency_complete_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_count_competencies",
    moodleFunction: "core_competency_count_competencies",
    description: "Moodle web service function `core_competency_count_competencies`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_count_competencies_in_course",
    moodleFunction: "core_competency_count_competencies_in_course",
    description: "Moodle web service function `core_competency_count_competencies_in_course`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_count_competencies_in_template",
    moodleFunction: "core_competency_count_competencies_in_template",
    description: "Moodle web service function `core_competency_count_competencies_in_template`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_count_competency_frameworks",
    moodleFunction: "core_competency_count_competency_frameworks",
    description: "Moodle web service function `core_competency_count_competency_frameworks`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_count_course_module_competencies",
    moodleFunction: "core_competency_count_course_module_competencies",
    description: "Moodle web service function `core_competency_count_course_module_competencies`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_count_courses_using_competency",
    moodleFunction: "core_competency_count_courses_using_competency",
    description: "Moodle web service function `core_competency_count_courses_using_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_count_templates",
    moodleFunction: "core_competency_count_templates",
    description: "Moodle web service function `core_competency_count_templates`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_count_templates_using_competency",
    moodleFunction: "core_competency_count_templates_using_competency",
    description: "Moodle web service function `core_competency_count_templates_using_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_create_competency",
    moodleFunction: "core_competency_create_competency",
    description: "Moodle web service function `core_competency_create_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_create_competency_framework",
    moodleFunction: "core_competency_create_competency_framework",
    description: "Moodle web service function `core_competency_create_competency_framework`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_create_plan",
    moodleFunction: "core_competency_create_plan",
    description: "Moodle web service function `core_competency_create_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_create_template",
    moodleFunction: "core_competency_create_template",
    description: "Moodle web service function `core_competency_create_template`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_create_user_evidence_competency",
    moodleFunction: "core_competency_create_user_evidence_competency",
    description: "Moodle web service function `core_competency_create_user_evidence_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_delete_competency",
    moodleFunction: "core_competency_delete_competency",
    description: "Moodle web service function `core_competency_delete_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_delete_competency_framework",
    moodleFunction: "core_competency_delete_competency_framework",
    description: "Moodle web service function `core_competency_delete_competency_framework`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_delete_evidence",
    moodleFunction: "core_competency_delete_evidence",
    description: "Moodle web service function `core_competency_delete_evidence`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_delete_plan",
    moodleFunction: "core_competency_delete_plan",
    description: "Moodle web service function `core_competency_delete_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_delete_template",
    moodleFunction: "core_competency_delete_template",
    description: "Moodle web service function `core_competency_delete_template`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_delete_user_evidence",
    moodleFunction: "core_competency_delete_user_evidence",
    description: "Moodle web service function `core_competency_delete_user_evidence`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_delete_user_evidence_competency",
    moodleFunction: "core_competency_delete_user_evidence_competency",
    description: "Moodle web service function `core_competency_delete_user_evidence_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_duplicate_competency_framework",
    moodleFunction: "core_competency_duplicate_competency_framework",
    description: "Moodle web service function `core_competency_duplicate_competency_framework`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_duplicate_template",
    moodleFunction: "core_competency_duplicate_template",
    description: "Moodle web service function `core_competency_duplicate_template`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_get_scale_values",
    moodleFunction: "core_competency_get_scale_values",
    description: "Moodle web service function `core_competency_get_scale_values`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_grade_competency",
    moodleFunction: "core_competency_grade_competency",
    description: "Moodle web service function `core_competency_grade_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_grade_competency_in_course",
    moodleFunction: "core_competency_grade_competency_in_course",
    description: "Moodle web service function `core_competency_grade_competency_in_course`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_grade_competency_in_plan",
    moodleFunction: "core_competency_grade_competency_in_plan",
    description: "Moodle web service function `core_competency_grade_competency_in_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_list_competencies",
    moodleFunction: "core_competency_list_competencies",
    description: "Moodle web service function `core_competency_list_competencies`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_list_competencies_in_template",
    moodleFunction: "core_competency_list_competencies_in_template",
    description: "Moodle web service function `core_competency_list_competencies_in_template`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_list_competency_frameworks",
    moodleFunction: "core_competency_list_competency_frameworks",
    description: "Moodle web service function `core_competency_list_competency_frameworks`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_list_course_competencies",
    moodleFunction: "core_competency_list_course_competencies",
    description: "Moodle web service function `core_competency_list_course_competencies`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_list_course_module_competencies",
    moodleFunction: "core_competency_list_course_module_competencies",
    description: "Moodle web service function `core_competency_list_course_module_competencies`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_list_plan_competencies",
    moodleFunction: "core_competency_list_plan_competencies",
    description: "Moodle web service function `core_competency_list_plan_competencies`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_list_templates",
    moodleFunction: "core_competency_list_templates",
    description: "Moodle web service function `core_competency_list_templates`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_list_templates_using_competency",
    moodleFunction: "core_competency_list_templates_using_competency",
    description: "Moodle web service function `core_competency_list_templates_using_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_list_user_plans",
    moodleFunction: "core_competency_list_user_plans",
    description: "Moodle web service function `core_competency_list_user_plans`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_move_down_competency",
    moodleFunction: "core_competency_move_down_competency",
    description: "Moodle web service function `core_competency_move_down_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_move_up_competency",
    moodleFunction: "core_competency_move_up_competency",
    description: "Moodle web service function `core_competency_move_up_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_plan_cancel_review_request",
    moodleFunction: "core_competency_plan_cancel_review_request",
    description: "Moodle web service function `core_competency_plan_cancel_review_request`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_plan_request_review",
    moodleFunction: "core_competency_plan_request_review",
    description: "Moodle web service function `core_competency_plan_request_review`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_plan_start_review",
    moodleFunction: "core_competency_plan_start_review",
    description: "Moodle web service function `core_competency_plan_start_review`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_plan_stop_review",
    moodleFunction: "core_competency_plan_stop_review",
    description: "Moodle web service function `core_competency_plan_stop_review`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_read_competency",
    moodleFunction: "core_competency_read_competency",
    description: "Moodle web service function `core_competency_read_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_read_competency_framework",
    moodleFunction: "core_competency_read_competency_framework",
    description: "Moodle web service function `core_competency_read_competency_framework`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_read_plan",
    moodleFunction: "core_competency_read_plan",
    description: "Moodle web service function `core_competency_read_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_read_template",
    moodleFunction: "core_competency_read_template",
    description: "Moodle web service function `core_competency_read_template`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_read_user_evidence",
    moodleFunction: "core_competency_read_user_evidence",
    description: "Moodle web service function `core_competency_read_user_evidence`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_remove_competency_from_course",
    moodleFunction: "core_competency_remove_competency_from_course",
    description: "Moodle web service function `core_competency_remove_competency_from_course`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_remove_competency_from_plan",
    moodleFunction: "core_competency_remove_competency_from_plan",
    description: "Moodle web service function `core_competency_remove_competency_from_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_remove_competency_from_template",
    moodleFunction: "core_competency_remove_competency_from_template",
    description: "Moodle web service function `core_competency_remove_competency_from_template`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_remove_related_competency",
    moodleFunction: "core_competency_remove_related_competency",
    description: "Moodle web service function `core_competency_remove_related_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_reopen_plan",
    moodleFunction: "core_competency_reopen_plan",
    description: "Moodle web service function `core_competency_reopen_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_reorder_course_competency",
    moodleFunction: "core_competency_reorder_course_competency",
    description: "Moodle web service function `core_competency_reorder_course_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_reorder_plan_competency",
    moodleFunction: "core_competency_reorder_plan_competency",
    description: "Moodle web service function `core_competency_reorder_plan_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_reorder_template_competency",
    moodleFunction: "core_competency_reorder_template_competency",
    description: "Moodle web service function `core_competency_reorder_template_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_request_review_of_user_evidence_linked_competencies",
    moodleFunction: "core_competency_request_review_of_user_evidence_linked_competencies",
    description: "Moodle web service function `core_competency_request_review_of_user_evidence_linked_competencies`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_search_competencies",
    moodleFunction: "core_competency_search_competencies",
    description: "Moodle web service function `core_competency_search_competencies`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_set_course_competency_ruleoutcome",
    moodleFunction: "core_competency_set_course_competency_ruleoutcome",
    description: "Moodle web service function `core_competency_set_course_competency_ruleoutcome`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_set_parent_competency",
    moodleFunction: "core_competency_set_parent_competency",
    description: "Moodle web service function `core_competency_set_parent_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_template_has_related_data",
    moodleFunction: "core_competency_template_has_related_data",
    description: "Moodle web service function `core_competency_template_has_related_data`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_template_viewed",
    moodleFunction: "core_competency_template_viewed",
    description: "Moodle web service function `core_competency_template_viewed`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_unapprove_plan",
    moodleFunction: "core_competency_unapprove_plan",
    description: "Moodle web service function `core_competency_unapprove_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_unlink_plan_from_template",
    moodleFunction: "core_competency_unlink_plan_from_template",
    description: "Moodle web service function `core_competency_unlink_plan_from_template`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_update_competency",
    moodleFunction: "core_competency_update_competency",
    description: "Moodle web service function `core_competency_update_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_update_competency_framework",
    moodleFunction: "core_competency_update_competency_framework",
    description: "Moodle web service function `core_competency_update_competency_framework`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_update_course_competency_settings",
    moodleFunction: "core_competency_update_course_competency_settings",
    description: "Moodle web service function `core_competency_update_course_competency_settings`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_update_plan",
    moodleFunction: "core_competency_update_plan",
    description: "Moodle web service function `core_competency_update_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_update_template",
    moodleFunction: "core_competency_update_template",
    description: "Moodle web service function `core_competency_update_template`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_user_competency_cancel_review_request",
    moodleFunction: "core_competency_user_competency_cancel_review_request",
    description: "Moodle web service function `core_competency_user_competency_cancel_review_request`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_user_competency_plan_viewed",
    moodleFunction: "core_competency_user_competency_plan_viewed",
    description: "Moodle web service function `core_competency_user_competency_plan_viewed`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_user_competency_request_review",
    moodleFunction: "core_competency_user_competency_request_review",
    description: "Moodle web service function `core_competency_user_competency_request_review`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_user_competency_start_review",
    moodleFunction: "core_competency_user_competency_start_review",
    description: "Moodle web service function `core_competency_user_competency_start_review`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_user_competency_stop_review",
    moodleFunction: "core_competency_user_competency_stop_review",
    description: "Moodle web service function `core_competency_user_competency_stop_review`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_user_competency_viewed",
    moodleFunction: "core_competency_user_competency_viewed",
    description: "Moodle web service function `core_competency_user_competency_viewed`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_user_competency_viewed_in_course",
    moodleFunction: "core_competency_user_competency_viewed_in_course",
    description: "Moodle web service function `core_competency_user_competency_viewed_in_course`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_competency_user_competency_viewed_in_plan",
    moodleFunction: "core_competency_user_competency_viewed_in_plan",
    description: "Moodle web service function `core_competency_user_competency_viewed_in_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
];
