import type { ToolSpec } from "../../types.js";

export const core_group_tools: ToolSpec[] = [
  {
    name: "core_group_add_group_members",
    moodleFunction: "core_group_add_group_members",
    description: "Moodle web service function `core_group_add_group_members`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_assign_grouping",
    moodleFunction: "core_group_assign_grouping",
    description: "Moodle web service function `core_group_assign_grouping`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_create_groupings",
    moodleFunction: "core_group_create_groupings",
    description: "Moodle web service function `core_group_create_groupings`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_create_groups",
    moodleFunction: "core_group_create_groups",
    description: "Moodle web service function `core_group_create_groups`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_delete_group_members",
    moodleFunction: "core_group_delete_group_members",
    description: "Moodle web service function `core_group_delete_group_members`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_delete_groupings",
    moodleFunction: "core_group_delete_groupings",
    description: "Moodle web service function `core_group_delete_groupings`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_delete_groups",
    moodleFunction: "core_group_delete_groups",
    description: "Moodle web service function `core_group_delete_groups`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_get_activity_allowed_groups",
    moodleFunction: "core_group_get_activity_allowed_groups",
    description: "Moodle web service function `core_group_get_activity_allowed_groups`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_get_activity_groupmode",
    moodleFunction: "core_group_get_activity_groupmode",
    description: "Moodle web service function `core_group_get_activity_groupmode`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_get_course_groupings",
    moodleFunction: "core_group_get_course_groupings",
    description: "Moodle web service function `core_group_get_course_groupings`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_get_course_groups",
    moodleFunction: "core_group_get_course_groups",
    description: "Moodle web service function `core_group_get_course_groups`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_get_course_user_groups",
    moodleFunction: "core_group_get_course_user_groups",
    description: "Moodle web service function `core_group_get_course_user_groups`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_get_group_members",
    moodleFunction: "core_group_get_group_members",
    description: "Moodle web service function `core_group_get_group_members`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_get_groupings",
    moodleFunction: "core_group_get_groupings",
    description: "Moodle web service function `core_group_get_groupings`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_get_groups",
    moodleFunction: "core_group_get_groups",
    description: "Moodle web service function `core_group_get_groups`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_get_groups_for_selector",
    moodleFunction: "core_group_get_groups_for_selector",
    description: "Moodle web service function `core_group_get_groups_for_selector`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_unassign_grouping",
    moodleFunction: "core_group_unassign_grouping",
    description: "Moodle web service function `core_group_unassign_grouping`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_update_groupings",
    moodleFunction: "core_group_update_groupings",
    description: "Moodle web service function `core_group_update_groupings`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_group_update_groups",
    moodleFunction: "core_group_update_groups",
    description: "Moodle web service function `core_group_update_groups`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
];
