import type { ToolSpec } from "../../types.js";

export const core_reportbuilder_tools: ToolSpec[] = [
  {
    name: "core_reportbuilder_audiences_delete",
    moodleFunction: "core_reportbuilder_audiences_delete",
    description: "Moodle web service function `core_reportbuilder_audiences_delete`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_can_view_system_report",
    moodleFunction: "core_reportbuilder_can_view_system_report",
    description: "Moodle web service function `core_reportbuilder_can_view_system_report`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_columns_add",
    moodleFunction: "core_reportbuilder_columns_add",
    description: "Moodle web service function `core_reportbuilder_columns_add`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_columns_delete",
    moodleFunction: "core_reportbuilder_columns_delete",
    description: "Moodle web service function `core_reportbuilder_columns_delete`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_columns_reorder",
    moodleFunction: "core_reportbuilder_columns_reorder",
    description: "Moodle web service function `core_reportbuilder_columns_reorder`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_columns_sort_get",
    moodleFunction: "core_reportbuilder_columns_sort_get",
    description: "Moodle web service function `core_reportbuilder_columns_sort_get`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_columns_sort_reorder",
    moodleFunction: "core_reportbuilder_columns_sort_reorder",
    description: "Moodle web service function `core_reportbuilder_columns_sort_reorder`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_columns_sort_toggle",
    moodleFunction: "core_reportbuilder_columns_sort_toggle",
    description: "Moodle web service function `core_reportbuilder_columns_sort_toggle`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_conditions_add",
    moodleFunction: "core_reportbuilder_conditions_add",
    description: "Moodle web service function `core_reportbuilder_conditions_add`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_conditions_delete",
    moodleFunction: "core_reportbuilder_conditions_delete",
    description: "Moodle web service function `core_reportbuilder_conditions_delete`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_conditions_reorder",
    moodleFunction: "core_reportbuilder_conditions_reorder",
    description: "Moodle web service function `core_reportbuilder_conditions_reorder`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_conditions_reset",
    moodleFunction: "core_reportbuilder_conditions_reset",
    description: "Moodle web service function `core_reportbuilder_conditions_reset`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_filters_add",
    moodleFunction: "core_reportbuilder_filters_add",
    description: "Moodle web service function `core_reportbuilder_filters_add`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_filters_delete",
    moodleFunction: "core_reportbuilder_filters_delete",
    description: "Moodle web service function `core_reportbuilder_filters_delete`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_filters_reorder",
    moodleFunction: "core_reportbuilder_filters_reorder",
    description: "Moodle web service function `core_reportbuilder_filters_reorder`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_filters_reset",
    moodleFunction: "core_reportbuilder_filters_reset",
    description: "Moodle web service function `core_reportbuilder_filters_reset`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_list_reports",
    moodleFunction: "core_reportbuilder_list_reports",
    description: "Moodle web service function `core_reportbuilder_list_reports`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_reports_delete",
    moodleFunction: "core_reportbuilder_reports_delete",
    description: "Moodle web service function `core_reportbuilder_reports_delete`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_reports_get",
    moodleFunction: "core_reportbuilder_reports_get",
    description: "Moodle web service function `core_reportbuilder_reports_get`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_retrieve_report",
    moodleFunction: "core_reportbuilder_retrieve_report",
    description: "Moodle web service function `core_reportbuilder_retrieve_report`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_retrieve_system_report",
    moodleFunction: "core_reportbuilder_retrieve_system_report",
    description: "Moodle web service function `core_reportbuilder_retrieve_system_report`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_schedules_delete",
    moodleFunction: "core_reportbuilder_schedules_delete",
    description: "Moodle web service function `core_reportbuilder_schedules_delete`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_schedules_send",
    moodleFunction: "core_reportbuilder_schedules_send",
    description: "Moodle web service function `core_reportbuilder_schedules_send`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_schedules_toggle",
    moodleFunction: "core_reportbuilder_schedules_toggle",
    description: "Moodle web service function `core_reportbuilder_schedules_toggle`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_set_filters",
    moodleFunction: "core_reportbuilder_set_filters",
    description: "Moodle web service function `core_reportbuilder_set_filters`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "core_reportbuilder_view_report",
    moodleFunction: "core_reportbuilder_view_report",
    description: "Moodle web service function `core_reportbuilder_view_report`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
];
