import type { ToolSpec } from "../../types.js";

export const tool_dataprivacy_tools: ToolSpec[] = [
  {
    name: "tool_dataprivacy_approve_data_request",
    moodleFunction: "tool_dataprivacy_approve_data_request",
    description: "Moodle web service function `tool_dataprivacy_approve_data_request`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_bulk_approve_data_requests",
    moodleFunction: "tool_dataprivacy_bulk_approve_data_requests",
    description: "Moodle web service function `tool_dataprivacy_bulk_approve_data_requests`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_bulk_deny_data_requests",
    moodleFunction: "tool_dataprivacy_bulk_deny_data_requests",
    description: "Moodle web service function `tool_dataprivacy_bulk_deny_data_requests`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_cancel_data_request",
    moodleFunction: "tool_dataprivacy_cancel_data_request",
    description: "Moodle web service function `tool_dataprivacy_cancel_data_request`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_confirm_contexts_for_deletion",
    moodleFunction: "tool_dataprivacy_confirm_contexts_for_deletion",
    description: "Moodle web service function `tool_dataprivacy_confirm_contexts_for_deletion`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_contact_dpo",
    moodleFunction: "tool_dataprivacy_contact_dpo",
    description: "Moodle web service function `tool_dataprivacy_contact_dpo`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_create_category_form",
    moodleFunction: "tool_dataprivacy_create_category_form",
    description: "Moodle web service function `tool_dataprivacy_create_category_form`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_create_data_request",
    moodleFunction: "tool_dataprivacy_create_data_request",
    description: "Moodle web service function `tool_dataprivacy_create_data_request`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_create_purpose_form",
    moodleFunction: "tool_dataprivacy_create_purpose_form",
    description: "Moodle web service function `tool_dataprivacy_create_purpose_form`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_delete_category",
    moodleFunction: "tool_dataprivacy_delete_category",
    description: "Moodle web service function `tool_dataprivacy_delete_category`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_delete_purpose",
    moodleFunction: "tool_dataprivacy_delete_purpose",
    description: "Moodle web service function `tool_dataprivacy_delete_purpose`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_deny_data_request",
    moodleFunction: "tool_dataprivacy_deny_data_request",
    description: "Moodle web service function `tool_dataprivacy_deny_data_request`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_get_access_information",
    moodleFunction: "tool_dataprivacy_get_access_information",
    description: "Moodle web service function `tool_dataprivacy_get_access_information`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_get_activity_options",
    moodleFunction: "tool_dataprivacy_get_activity_options",
    description: "Moodle web service function `tool_dataprivacy_get_activity_options`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_get_category_options",
    moodleFunction: "tool_dataprivacy_get_category_options",
    description: "Moodle web service function `tool_dataprivacy_get_category_options`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_get_data_request",
    moodleFunction: "tool_dataprivacy_get_data_request",
    description: "Moodle web service function `tool_dataprivacy_get_data_request`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_get_data_requests",
    moodleFunction: "tool_dataprivacy_get_data_requests",
    description: "Moodle web service function `tool_dataprivacy_get_data_requests`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_get_purpose_options",
    moodleFunction: "tool_dataprivacy_get_purpose_options",
    description: "Moodle web service function `tool_dataprivacy_get_purpose_options`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_get_users",
    moodleFunction: "tool_dataprivacy_get_users",
    description: "Moodle web service function `tool_dataprivacy_get_users`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_mark_complete",
    moodleFunction: "tool_dataprivacy_mark_complete",
    description: "Moodle web service function `tool_dataprivacy_mark_complete`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_set_context_defaults",
    moodleFunction: "tool_dataprivacy_set_context_defaults",
    description: "Moodle web service function `tool_dataprivacy_set_context_defaults`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_set_context_form",
    moodleFunction: "tool_dataprivacy_set_context_form",
    description: "Moodle web service function `tool_dataprivacy_set_context_form`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_set_contextlevel_form",
    moodleFunction: "tool_dataprivacy_set_contextlevel_form",
    description: "Moodle web service function `tool_dataprivacy_set_contextlevel_form`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_submit_selected_courses_form",
    moodleFunction: "tool_dataprivacy_submit_selected_courses_form",
    description: "Moodle web service function `tool_dataprivacy_submit_selected_courses_form`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
  {
    name: "tool_dataprivacy_tree_extra_branches",
    moodleFunction: "tool_dataprivacy_tree_extra_branches",
    description: "Moodle web service function `tool_dataprivacy_tree_extra_branches`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager"],
    examples: { minimal: {} },
  },
];
