import type { ToolSpec } from "../../types.js";

export const tool_lp_tools: ToolSpec[] = [
  {
    name: "tool_lp_data_for_competencies_manage_page",
    moodleFunction: "tool_lp_data_for_competencies_manage_page",
    description: "Moodle web service function `tool_lp_data_for_competencies_manage_page`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_data_for_competency_frameworks_manage_page",
    moodleFunction: "tool_lp_data_for_competency_frameworks_manage_page",
    description: "Moodle web service function `tool_lp_data_for_competency_frameworks_manage_page`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_data_for_competency_summary",
    moodleFunction: "tool_lp_data_for_competency_summary",
    description: "Moodle web service function `tool_lp_data_for_competency_summary`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_data_for_course_competencies_page",
    moodleFunction: "tool_lp_data_for_course_competencies_page",
    description: "Moodle web service function `tool_lp_data_for_course_competencies_page`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_data_for_plan_page",
    moodleFunction: "tool_lp_data_for_plan_page",
    description: "Moodle web service function `tool_lp_data_for_plan_page`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_data_for_plans_page",
    moodleFunction: "tool_lp_data_for_plans_page",
    description: "Moodle web service function `tool_lp_data_for_plans_page`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_data_for_related_competencies_section",
    moodleFunction: "tool_lp_data_for_related_competencies_section",
    description: "Moodle web service function `tool_lp_data_for_related_competencies_section`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_data_for_template_competencies_page",
    moodleFunction: "tool_lp_data_for_template_competencies_page",
    description: "Moodle web service function `tool_lp_data_for_template_competencies_page`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_data_for_templates_manage_page",
    moodleFunction: "tool_lp_data_for_templates_manage_page",
    description: "Moodle web service function `tool_lp_data_for_templates_manage_page`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_data_for_user_competency_summary",
    moodleFunction: "tool_lp_data_for_user_competency_summary",
    description: "Moodle web service function `tool_lp_data_for_user_competency_summary`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_data_for_user_competency_summary_in_course",
    moodleFunction: "tool_lp_data_for_user_competency_summary_in_course",
    description: "Moodle web service function `tool_lp_data_for_user_competency_summary_in_course`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_data_for_user_competency_summary_in_plan",
    moodleFunction: "tool_lp_data_for_user_competency_summary_in_plan",
    description: "Moodle web service function `tool_lp_data_for_user_competency_summary_in_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_data_for_user_evidence_list_page",
    moodleFunction: "tool_lp_data_for_user_evidence_list_page",
    description: "Moodle web service function `tool_lp_data_for_user_evidence_list_page`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_data_for_user_evidence_page",
    moodleFunction: "tool_lp_data_for_user_evidence_page",
    description: "Moodle web service function `tool_lp_data_for_user_evidence_page`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_list_courses_using_competency",
    moodleFunction: "tool_lp_list_courses_using_competency",
    description: "Moodle web service function `tool_lp_list_courses_using_competency`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_search_cohorts",
    moodleFunction: "tool_lp_search_cohorts",
    description: "Moodle web service function `tool_lp_search_cohorts`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "tool_lp_search_users",
    moodleFunction: "tool_lp_search_users",
    description: "Moodle web service function `tool_lp_search_users`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
];
