import type { ToolSpec } from "../../types.js";

export const mod_assign_tools: ToolSpec[] = [
  {
    name: "mod_assign_copy_previous_attempt",
    moodleFunction: "mod_assign_copy_previous_attempt",
    description: "Moodle web service function `mod_assign_copy_previous_attempt`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_get_assignments",
    moodleFunction: "mod_assign_get_assignments",
    description: "Moodle web service function `mod_assign_get_assignments`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_get_grades",
    moodleFunction: "mod_assign_get_grades",
    description: "Moodle web service function `mod_assign_get_grades`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_get_participant",
    moodleFunction: "mod_assign_get_participant",
    description: "Moodle web service function `mod_assign_get_participant`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_get_submission_status",
    moodleFunction: "mod_assign_get_submission_status",
    description: "Moodle web service function `mod_assign_get_submission_status`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_get_submissions",
    moodleFunction: "mod_assign_get_submissions",
    description: "Moodle web service function `mod_assign_get_submissions`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_get_user_flags",
    moodleFunction: "mod_assign_get_user_flags",
    description: "Moodle web service function `mod_assign_get_user_flags`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_get_user_mappings",
    moodleFunction: "mod_assign_get_user_mappings",
    description: "Moodle web service function `mod_assign_get_user_mappings`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_list_participants",
    moodleFunction: "mod_assign_list_participants",
    description: "Moodle web service function `mod_assign_list_participants`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_lock_submissions",
    moodleFunction: "mod_assign_lock_submissions",
    description: "Moodle web service function `mod_assign_lock_submissions`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_remove_submission",
    moodleFunction: "mod_assign_remove_submission",
    description: "Moodle web service function `mod_assign_remove_submission`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_reveal_identities",
    moodleFunction: "mod_assign_reveal_identities",
    description: "Moodle web service function `mod_assign_reveal_identities`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_revert_submissions_to_draft",
    moodleFunction: "mod_assign_revert_submissions_to_draft",
    description: "Moodle web service function `mod_assign_revert_submissions_to_draft`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_save_grade",
    moodleFunction: "mod_assign_save_grade",
    description: "Moodle web service function `mod_assign_save_grade`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_save_grades",
    moodleFunction: "mod_assign_save_grades",
    description: "Moodle web service function `mod_assign_save_grades`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_save_submission",
    moodleFunction: "mod_assign_save_submission",
    description: "Moodle web service function `mod_assign_save_submission`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_save_user_extensions",
    moodleFunction: "mod_assign_save_user_extensions",
    description: "Moodle web service function `mod_assign_save_user_extensions`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_set_user_flags",
    moodleFunction: "mod_assign_set_user_flags",
    description: "Moodle web service function `mod_assign_set_user_flags`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_start_submission",
    moodleFunction: "mod_assign_start_submission",
    description: "Moodle web service function `mod_assign_start_submission`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_submit_for_grading",
    moodleFunction: "mod_assign_submit_for_grading",
    description: "Moodle web service function `mod_assign_submit_for_grading`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_submit_grading_form",
    moodleFunction: "mod_assign_submit_grading_form",
    description: "Moodle web service function `mod_assign_submit_grading_form`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_unlock_submissions",
    moodleFunction: "mod_assign_unlock_submissions",
    description: "Moodle web service function `mod_assign_unlock_submissions`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_view_assign",
    moodleFunction: "mod_assign_view_assign",
    description: "Moodle web service function `mod_assign_view_assign`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_view_grading_table",
    moodleFunction: "mod_assign_view_grading_table",
    description: "Moodle web service function `mod_assign_view_grading_table`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_assign_view_submission_status",
    moodleFunction: "mod_assign_view_submission_status",
    description: "Moodle web service function `mod_assign_view_submission_status`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
];
