import type { ToolSpec } from "../../types.js";

export const mod_data_tools: ToolSpec[] = [
  {
    name: "mod_data_add_entry",
    moodleFunction: "mod_data_add_entry",
    description: "Moodle web service function `mod_data_add_entry`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_data_approve_entry",
    moodleFunction: "mod_data_approve_entry",
    description: "Moodle web service function `mod_data_approve_entry`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_data_delete_entry",
    moodleFunction: "mod_data_delete_entry",
    description: "Moodle web service function `mod_data_delete_entry`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_data_delete_saved_preset",
    moodleFunction: "mod_data_delete_saved_preset",
    description: "Moodle web service function `mod_data_delete_saved_preset`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_data_get_data_access_information",
    moodleFunction: "mod_data_get_data_access_information",
    description: "Moodle web service function `mod_data_get_data_access_information`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_data_get_databases_by_courses",
    moodleFunction: "mod_data_get_databases_by_courses",
    description: "Moodle web service function `mod_data_get_databases_by_courses`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_data_get_entries",
    moodleFunction: "mod_data_get_entries",
    description: "Moodle web service function `mod_data_get_entries`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_data_get_entry",
    moodleFunction: "mod_data_get_entry",
    description: "Moodle web service function `mod_data_get_entry`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_data_get_fields",
    moodleFunction: "mod_data_get_fields",
    description: "Moodle web service function `mod_data_get_fields`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_data_get_mapping_information",
    moodleFunction: "mod_data_get_mapping_information",
    description: "Moodle web service function `mod_data_get_mapping_information`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_data_search_entries",
    moodleFunction: "mod_data_search_entries",
    description: "Moodle web service function `mod_data_search_entries`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_data_update_entry",
    moodleFunction: "mod_data_update_entry",
    description: "Moodle web service function `mod_data_update_entry`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_data_view_database",
    moodleFunction: "mod_data_view_database",
    description: "Moodle web service function `mod_data_view_database`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
];
