import type { ToolSpec } from "../../types.js";

export const mod_feedback_tools: ToolSpec[] = [
  {
    name: "mod_feedback_get_analysis",
    moodleFunction: "mod_feedback_get_analysis",
    description: "Moodle web service function `mod_feedback_get_analysis`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_get_current_completed_tmp",
    moodleFunction: "mod_feedback_get_current_completed_tmp",
    description: "Moodle web service function `mod_feedback_get_current_completed_tmp`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_get_feedback_access_information",
    moodleFunction: "mod_feedback_get_feedback_access_information",
    description: "Moodle web service function `mod_feedback_get_feedback_access_information`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_get_feedbacks_by_courses",
    moodleFunction: "mod_feedback_get_feedbacks_by_courses",
    description: "Moodle web service function `mod_feedback_get_feedbacks_by_courses`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_get_finished_responses",
    moodleFunction: "mod_feedback_get_finished_responses",
    description: "Moodle web service function `mod_feedback_get_finished_responses`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_get_items",
    moodleFunction: "mod_feedback_get_items",
    description: "Moodle web service function `mod_feedback_get_items`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_get_last_completed",
    moodleFunction: "mod_feedback_get_last_completed",
    description: "Moodle web service function `mod_feedback_get_last_completed`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_get_non_respondents",
    moodleFunction: "mod_feedback_get_non_respondents",
    description: "Moodle web service function `mod_feedback_get_non_respondents`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_get_page_items",
    moodleFunction: "mod_feedback_get_page_items",
    description: "Moodle web service function `mod_feedback_get_page_items`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_get_responses_analysis",
    moodleFunction: "mod_feedback_get_responses_analysis",
    description: "Moodle web service function `mod_feedback_get_responses_analysis`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_get_unfinished_responses",
    moodleFunction: "mod_feedback_get_unfinished_responses",
    description: "Moodle web service function `mod_feedback_get_unfinished_responses`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_launch_feedback",
    moodleFunction: "mod_feedback_launch_feedback",
    description: "Moodle web service function `mod_feedback_launch_feedback`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_process_page",
    moodleFunction: "mod_feedback_process_page",
    description: "Moodle web service function `mod_feedback_process_page`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_questions_reorder",
    moodleFunction: "mod_feedback_questions_reorder",
    description: "Moodle web service function `mod_feedback_questions_reorder`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_feedback_view_feedback",
    moodleFunction: "mod_feedback_view_feedback",
    description: "Moodle web service function `mod_feedback_view_feedback`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
];
