import type { ToolSpec } from "../../types.js";

export const mod_forum_tools: ToolSpec[] = [
  {
    name: "mod_forum_add_discussion",
    moodleFunction: "mod_forum_add_discussion",
    description: "Moodle web service function `mod_forum_add_discussion`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_add_discussion_post",
    moodleFunction: "mod_forum_add_discussion_post",
    description: "Moodle web service function `mod_forum_add_discussion_post`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_can_add_discussion",
    moodleFunction: "mod_forum_can_add_discussion",
    description: "Moodle web service function `mod_forum_can_add_discussion`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_delete_post",
    moodleFunction: "mod_forum_delete_post",
    description: "Moodle web service function `mod_forum_delete_post`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_get_discussion_post",
    moodleFunction: "mod_forum_get_discussion_post",
    description: "Moodle web service function `mod_forum_get_discussion_post`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_get_discussion_posts",
    moodleFunction: "mod_forum_get_discussion_posts",
    description: "Moodle web service function `mod_forum_get_discussion_posts`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_get_discussion_posts_by_userid",
    moodleFunction: "mod_forum_get_discussion_posts_by_userid",
    description: "Moodle web service function `mod_forum_get_discussion_posts_by_userid`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_get_forum_access_information",
    moodleFunction: "mod_forum_get_forum_access_information",
    description: "Moodle web service function `mod_forum_get_forum_access_information`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_get_forum_discussions",
    moodleFunction: "mod_forum_get_forum_discussions",
    description: "Moodle web service function `mod_forum_get_forum_discussions`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_get_forums_by_courses",
    moodleFunction: "mod_forum_get_forums_by_courses",
    description: "Moodle web service function `mod_forum_get_forums_by_courses`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_prepare_draft_area_for_post",
    moodleFunction: "mod_forum_prepare_draft_area_for_post",
    description: "Moodle web service function `mod_forum_prepare_draft_area_for_post`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_set_forum_subscription",
    moodleFunction: "mod_forum_set_forum_subscription",
    description: "Moodle web service function `mod_forum_set_forum_subscription`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_set_forum_tracking",
    moodleFunction: "mod_forum_set_forum_tracking",
    description: "Moodle web service function `mod_forum_set_forum_tracking`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_set_lock_state",
    moodleFunction: "mod_forum_set_lock_state",
    description: "Moodle web service function `mod_forum_set_lock_state`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_set_pin_state",
    moodleFunction: "mod_forum_set_pin_state",
    description: "Moodle web service function `mod_forum_set_pin_state`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_set_subscription_state",
    moodleFunction: "mod_forum_set_subscription_state",
    description: "Moodle web service function `mod_forum_set_subscription_state`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_toggle_favourite_state",
    moodleFunction: "mod_forum_toggle_favourite_state",
    description: "Moodle web service function `mod_forum_toggle_favourite_state`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_update_discussion_post",
    moodleFunction: "mod_forum_update_discussion_post",
    description: "Moodle web service function `mod_forum_update_discussion_post`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_view_forum",
    moodleFunction: "mod_forum_view_forum",
    description: "Moodle web service function `mod_forum_view_forum`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_forum_view_forum_discussion",
    moodleFunction: "mod_forum_view_forum_discussion",
    description: "Moodle web service function `mod_forum_view_forum_discussion`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
];
