import type { ToolSpec } from "../../types.js";

export const mod_glossary_tools: ToolSpec[] = [
  {
    name: "mod_glossary_add_entry",
    moodleFunction: "mod_glossary_add_entry",
    description: "Moodle web service function `mod_glossary_add_entry`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_delete_entry",
    moodleFunction: "mod_glossary_delete_entry",
    description: "Moodle web service function `mod_glossary_delete_entry`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_get_authors",
    moodleFunction: "mod_glossary_get_authors",
    description: "Moodle web service function `mod_glossary_get_authors`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_get_categories",
    moodleFunction: "mod_glossary_get_categories",
    description: "Moodle web service function `mod_glossary_get_categories`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_get_entries_by_author",
    moodleFunction: "mod_glossary_get_entries_by_author",
    description: "Moodle web service function `mod_glossary_get_entries_by_author`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_get_entries_by_author_id",
    moodleFunction: "mod_glossary_get_entries_by_author_id",
    description: "Moodle web service function `mod_glossary_get_entries_by_author_id`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_get_entries_by_category",
    moodleFunction: "mod_glossary_get_entries_by_category",
    description: "Moodle web service function `mod_glossary_get_entries_by_category`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_get_entries_by_date",
    moodleFunction: "mod_glossary_get_entries_by_date",
    description: "Moodle web service function `mod_glossary_get_entries_by_date`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_get_entries_by_letter",
    moodleFunction: "mod_glossary_get_entries_by_letter",
    description: "Moodle web service function `mod_glossary_get_entries_by_letter`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_get_entries_by_search",
    moodleFunction: "mod_glossary_get_entries_by_search",
    description: "Moodle web service function `mod_glossary_get_entries_by_search`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_get_entries_by_term",
    moodleFunction: "mod_glossary_get_entries_by_term",
    description: "Moodle web service function `mod_glossary_get_entries_by_term`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_get_entries_to_approve",
    moodleFunction: "mod_glossary_get_entries_to_approve",
    description: "Moodle web service function `mod_glossary_get_entries_to_approve`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_get_entry_by_id",
    moodleFunction: "mod_glossary_get_entry_by_id",
    description: "Moodle web service function `mod_glossary_get_entry_by_id`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_get_glossaries_by_courses",
    moodleFunction: "mod_glossary_get_glossaries_by_courses",
    description: "Moodle web service function `mod_glossary_get_glossaries_by_courses`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_prepare_entry_for_edition",
    moodleFunction: "mod_glossary_prepare_entry_for_edition",
    description: "Moodle web service function `mod_glossary_prepare_entry_for_edition`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_update_entry",
    moodleFunction: "mod_glossary_update_entry",
    description: "Moodle web service function `mod_glossary_update_entry`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_view_entry",
    moodleFunction: "mod_glossary_view_entry",
    description: "Moodle web service function `mod_glossary_view_entry`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_glossary_view_glossary",
    moodleFunction: "mod_glossary_view_glossary",
    description: "Moodle web service function `mod_glossary_view_glossary`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
];
