import type { ToolSpec } from "../../types.js";

export const mod_lesson_tools: ToolSpec[] = [
  {
    name: "mod_lesson_finish_attempt",
    moodleFunction: "mod_lesson_finish_attempt",
    description: "Moodle web service function `mod_lesson_finish_attempt`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_get_attempts_overview",
    moodleFunction: "mod_lesson_get_attempts_overview",
    description: "Moodle web service function `mod_lesson_get_attempts_overview`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_get_content_pages_viewed",
    moodleFunction: "mod_lesson_get_content_pages_viewed",
    description: "Moodle web service function `mod_lesson_get_content_pages_viewed`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_get_lesson",
    moodleFunction: "mod_lesson_get_lesson",
    description: "Moodle web service function `mod_lesson_get_lesson`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_get_lesson_access_information",
    moodleFunction: "mod_lesson_get_lesson_access_information",
    description: "Moodle web service function `mod_lesson_get_lesson_access_information`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_get_lessons_by_courses",
    moodleFunction: "mod_lesson_get_lessons_by_courses",
    description: "Moodle web service function `mod_lesson_get_lessons_by_courses`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_get_page_data",
    moodleFunction: "mod_lesson_get_page_data",
    description: "Moodle web service function `mod_lesson_get_page_data`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_get_pages",
    moodleFunction: "mod_lesson_get_pages",
    description: "Moodle web service function `mod_lesson_get_pages`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_get_pages_possible_jumps",
    moodleFunction: "mod_lesson_get_pages_possible_jumps",
    description: "Moodle web service function `mod_lesson_get_pages_possible_jumps`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_get_questions_attempts",
    moodleFunction: "mod_lesson_get_questions_attempts",
    description: "Moodle web service function `mod_lesson_get_questions_attempts`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_get_user_attempt",
    moodleFunction: "mod_lesson_get_user_attempt",
    description: "Moodle web service function `mod_lesson_get_user_attempt`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_get_user_attempt_grade",
    moodleFunction: "mod_lesson_get_user_attempt_grade",
    description: "Moodle web service function `mod_lesson_get_user_attempt_grade`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_get_user_grade",
    moodleFunction: "mod_lesson_get_user_grade",
    description: "Moodle web service function `mod_lesson_get_user_grade`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_get_user_timers",
    moodleFunction: "mod_lesson_get_user_timers",
    description: "Moodle web service function `mod_lesson_get_user_timers`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_launch_attempt",
    moodleFunction: "mod_lesson_launch_attempt",
    description: "Moodle web service function `mod_lesson_launch_attempt`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_process_page",
    moodleFunction: "mod_lesson_process_page",
    description: "Moodle web service function `mod_lesson_process_page`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lesson_view_lesson",
    moodleFunction: "mod_lesson_view_lesson",
    description: "Moodle web service function `mod_lesson_view_lesson`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
];
