import type { ToolSpec } from "../../types.js";

export const mod_lti_tools: ToolSpec[] = [
  {
    name: "mod_lti_create_tool_proxy",
    moodleFunction: "mod_lti_create_tool_proxy",
    description: "Moodle web service function `mod_lti_create_tool_proxy`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_create_tool_type",
    moodleFunction: "mod_lti_create_tool_type",
    description: "Moodle web service function `mod_lti_create_tool_type`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_delete_course_tool_type",
    moodleFunction: "mod_lti_delete_course_tool_type",
    description: "Moodle web service function `mod_lti_delete_course_tool_type`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_delete_tool_proxy",
    moodleFunction: "mod_lti_delete_tool_proxy",
    description: "Moodle web service function `mod_lti_delete_tool_proxy`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_delete_tool_type",
    moodleFunction: "mod_lti_delete_tool_type",
    description: "Moodle web service function `mod_lti_delete_tool_type`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_get_ltis_by_courses",
    moodleFunction: "mod_lti_get_ltis_by_courses",
    description: "Moodle web service function `mod_lti_get_ltis_by_courses`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_get_tool_launch_data",
    moodleFunction: "mod_lti_get_tool_launch_data",
    description: "Moodle web service function `mod_lti_get_tool_launch_data`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_get_tool_proxies",
    moodleFunction: "mod_lti_get_tool_proxies",
    description: "Moodle web service function `mod_lti_get_tool_proxies`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_get_tool_proxy_registration_request",
    moodleFunction: "mod_lti_get_tool_proxy_registration_request",
    description: "Moodle web service function `mod_lti_get_tool_proxy_registration_request`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_get_tool_types",
    moodleFunction: "mod_lti_get_tool_types",
    description: "Moodle web service function `mod_lti_get_tool_types`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_get_tool_types_and_proxies",
    moodleFunction: "mod_lti_get_tool_types_and_proxies",
    description: "Moodle web service function `mod_lti_get_tool_types_and_proxies`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_get_tool_types_and_proxies_count",
    moodleFunction: "mod_lti_get_tool_types_and_proxies_count",
    description: "Moodle web service function `mod_lti_get_tool_types_and_proxies_count`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_is_cartridge",
    moodleFunction: "mod_lti_is_cartridge",
    description: "Moodle web service function `mod_lti_is_cartridge`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_toggle_showinactivitychooser",
    moodleFunction: "mod_lti_toggle_showinactivitychooser",
    description: "Moodle web service function `mod_lti_toggle_showinactivitychooser`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_update_tool_type",
    moodleFunction: "mod_lti_update_tool_type",
    description: "Moodle web service function `mod_lti_update_tool_type`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_lti_view_lti",
    moodleFunction: "mod_lti_view_lti",
    description: "Moodle web service function `mod_lti_view_lti`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
];
