import type { ToolSpec } from "../../types.js";

export const mod_quiz_tools: ToolSpec[] = [
  {
    name: "mod_quiz_add_random_questions",
    moodleFunction: "mod_quiz_add_random_questions",
    description: "Moodle web service function `mod_quiz_add_random_questions`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_create_grade_item_per_section",
    moodleFunction: "mod_quiz_create_grade_item_per_section",
    description: "Moodle web service function `mod_quiz_create_grade_item_per_section`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_create_grade_items",
    moodleFunction: "mod_quiz_create_grade_items",
    description: "Moodle web service function `mod_quiz_create_grade_items`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_delete_grade_items",
    moodleFunction: "mod_quiz_delete_grade_items",
    description: "Moodle web service function `mod_quiz_delete_grade_items`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_delete_overrides",
    moodleFunction: "mod_quiz_delete_overrides",
    description: "Moodle web service function `mod_quiz_delete_overrides`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_attempt_access_information",
    moodleFunction: "mod_quiz_get_attempt_access_information",
    description: "Moodle web service function `mod_quiz_get_attempt_access_information`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_attempt_data",
    moodleFunction: "mod_quiz_get_attempt_data",
    description: "Moodle web service function `mod_quiz_get_attempt_data`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_attempt_review",
    moodleFunction: "mod_quiz_get_attempt_review",
    description: "Moodle web service function `mod_quiz_get_attempt_review`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_attempt_summary",
    moodleFunction: "mod_quiz_get_attempt_summary",
    description: "Moodle web service function `mod_quiz_get_attempt_summary`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_combined_review_options",
    moodleFunction: "mod_quiz_get_combined_review_options",
    description: "Moodle web service function `mod_quiz_get_combined_review_options`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_edit_grading_page_data",
    moodleFunction: "mod_quiz_get_edit_grading_page_data",
    description: "Moodle web service function `mod_quiz_get_edit_grading_page_data`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_overrides",
    moodleFunction: "mod_quiz_get_overrides",
    description: "Moodle web service function `mod_quiz_get_overrides`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_quiz_access_information",
    moodleFunction: "mod_quiz_get_quiz_access_information",
    description: "Moodle web service function `mod_quiz_get_quiz_access_information`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_quiz_feedback_for_grade",
    moodleFunction: "mod_quiz_get_quiz_feedback_for_grade",
    description: "Moodle web service function `mod_quiz_get_quiz_feedback_for_grade`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_quiz_required_qtypes",
    moodleFunction: "mod_quiz_get_quiz_required_qtypes",
    description: "Moodle web service function `mod_quiz_get_quiz_required_qtypes`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_quizzes_by_courses",
    moodleFunction: "mod_quiz_get_quizzes_by_courses",
    description: "Moodle web service function `mod_quiz_get_quizzes_by_courses`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_reopen_attempt_confirmation",
    moodleFunction: "mod_quiz_get_reopen_attempt_confirmation",
    description: "Moodle web service function `mod_quiz_get_reopen_attempt_confirmation`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_user_attempts",
    moodleFunction: "mod_quiz_get_user_attempts",
    description: "Moodle web service function `mod_quiz_get_user_attempts`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_user_best_grade",
    moodleFunction: "mod_quiz_get_user_best_grade",
    description: "Moodle web service function `mod_quiz_get_user_best_grade`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_get_user_quiz_attempts",
    moodleFunction: "mod_quiz_get_user_quiz_attempts",
    description: "Moodle web service function `mod_quiz_get_user_quiz_attempts`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_process_attempt",
    moodleFunction: "mod_quiz_process_attempt",
    description: "Moodle web service function `mod_quiz_process_attempt`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_reopen_attempt",
    moodleFunction: "mod_quiz_reopen_attempt",
    description: "Moodle web service function `mod_quiz_reopen_attempt`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_save_attempt",
    moodleFunction: "mod_quiz_save_attempt",
    description: "Moodle web service function `mod_quiz_save_attempt`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_save_overrides",
    moodleFunction: "mod_quiz_save_overrides",
    description: "Moodle web service function `mod_quiz_save_overrides`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_set_question_version",
    moodleFunction: "mod_quiz_set_question_version",
    description: "Moodle web service function `mod_quiz_set_question_version`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_start_attempt",
    moodleFunction: "mod_quiz_start_attempt",
    description: "Moodle web service function `mod_quiz_start_attempt`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_update_filter_condition",
    moodleFunction: "mod_quiz_update_filter_condition",
    description: "Moodle web service function `mod_quiz_update_filter_condition`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_update_grade_items",
    moodleFunction: "mod_quiz_update_grade_items",
    description: "Moodle web service function `mod_quiz_update_grade_items`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_update_slots",
    moodleFunction: "mod_quiz_update_slots",
    description: "Moodle web service function `mod_quiz_update_slots`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_view_attempt",
    moodleFunction: "mod_quiz_view_attempt",
    description: "Moodle web service function `mod_quiz_view_attempt`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_view_attempt_review",
    moodleFunction: "mod_quiz_view_attempt_review",
    description: "Moodle web service function `mod_quiz_view_attempt_review`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_view_attempt_summary",
    moodleFunction: "mod_quiz_view_attempt_summary",
    description: "Moodle web service function `mod_quiz_view_attempt_summary`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_quiz_view_quiz",
    moodleFunction: "mod_quiz_view_quiz",
    description: "Moodle web service function `mod_quiz_view_quiz`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
];
