import type { ToolSpec } from "../../types.js";

export const mod_workshop_tools: ToolSpec[] = [
  {
    name: "mod_workshop_add_submission",
    moodleFunction: "mod_workshop_add_submission",
    description: "Moodle web service function `mod_workshop_add_submission`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_delete_submission",
    moodleFunction: "mod_workshop_delete_submission",
    description: "Moodle web service function `mod_workshop_delete_submission`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_evaluate_assessment",
    moodleFunction: "mod_workshop_evaluate_assessment",
    description: "Moodle web service function `mod_workshop_evaluate_assessment`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_evaluate_submission",
    moodleFunction: "mod_workshop_evaluate_submission",
    description: "Moodle web service function `mod_workshop_evaluate_submission`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_get_assessment",
    moodleFunction: "mod_workshop_get_assessment",
    description: "Moodle web service function `mod_workshop_get_assessment`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_get_assessment_form_definition",
    moodleFunction: "mod_workshop_get_assessment_form_definition",
    description: "Moodle web service function `mod_workshop_get_assessment_form_definition`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_get_grades",
    moodleFunction: "mod_workshop_get_grades",
    description: "Moodle web service function `mod_workshop_get_grades`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_get_grades_report",
    moodleFunction: "mod_workshop_get_grades_report",
    description: "Moodle web service function `mod_workshop_get_grades_report`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_get_reviewer_assessments",
    moodleFunction: "mod_workshop_get_reviewer_assessments",
    description: "Moodle web service function `mod_workshop_get_reviewer_assessments`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_get_submission",
    moodleFunction: "mod_workshop_get_submission",
    description: "Moodle web service function `mod_workshop_get_submission`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_get_submission_assessments",
    moodleFunction: "mod_workshop_get_submission_assessments",
    description: "Moodle web service function `mod_workshop_get_submission_assessments`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_get_submissions",
    moodleFunction: "mod_workshop_get_submissions",
    description: "Moodle web service function `mod_workshop_get_submissions`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_get_user_plan",
    moodleFunction: "mod_workshop_get_user_plan",
    description: "Moodle web service function `mod_workshop_get_user_plan`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_get_workshop_access_information",
    moodleFunction: "mod_workshop_get_workshop_access_information",
    description: "Moodle web service function `mod_workshop_get_workshop_access_information`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_get_workshops_by_courses",
    moodleFunction: "mod_workshop_get_workshops_by_courses",
    description: "Moodle web service function `mod_workshop_get_workshops_by_courses`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_update_assessment",
    moodleFunction: "mod_workshop_update_assessment",
    description: "Moodle web service function `mod_workshop_update_assessment`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_update_submission",
    moodleFunction: "mod_workshop_update_submission",
    description: "Moodle web service function `mod_workshop_update_submission`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_view_submission",
    moodleFunction: "mod_workshop_view_submission",
    description: "Moodle web service function `mod_workshop_view_submission`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
  {
    name: "mod_workshop_view_workshop",
    moodleFunction: "mod_workshop_view_workshop",
    description: "Moodle web service function `mod_workshop_view_workshop`.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: true,
    },
    allowedRoles: ["admin","manager","editingteacher","teacher","student","user"],
    examples: { minimal: {} },
  },
];
